### ISSUE TITLE
Request: Horizon Zero Dawn (Basic Edition)

### ISSUE THREAD

**Issue by trowicia** [Tustin/PlayStationDiscord-Games#1]
Hi Tustin, this isn't an issue with the RPC tool, but a subtle request. Can you add Horizon Zero Dawn's non-complete edition icon to the list of supported games if it's not too much to ask for?

**Comment by Tustin** [comment]
Sure, I'm surprised it didn't get picked up by the script tbh. I need to do some more work with this before it's ready to be used by the program but I'll make sure that game gets added. 👍

**Comment by eldexterr** [comment]
https://github.com/Tustin/PlayStationDiscord-Games/pull/53
