### ISSUE TITLE
So is this project just dead?

### ISSUE THREAD

**Issue by timothymowens** [Tustin/PlayStationDiscord-Games#140]
There are 70 pull requests going back over a year now.  What's the deal?

**Comment by sirzechs753** [comment]
This repo hasn't been updated since Nov 2020. For anyone who want to contribute I've [forked](https://github.com/sirzechs753/PlayStationDiscord-Games) this repo and currently maintaining the supported games update.

**Comment by joshlopes** [comment]
@Tustin Any reason why you are not updating/accepting PRs i see that u are accepting other PRs in the other repos but not on this one? I guess @sirzechs753 can help since his forked version has so many more games than yours probably the 73 games you have there pending...
