### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mindesik** [Tustin/PlayStationDiscord-Games#2]
Why not to scrape all of "All games" pages?

**Comment by Tustin** [comment]
Just saw this -- I could do this actually. When I originally wrote the script, I figured it would find about 150 games (which is the max amount of art assets you can upload to a Discord application) but instead it only ended up being ~100. I'll hack on the script a bit more and have it just grab a bunch of the newest games, regardless of ratings/price.

**Comment by mindesik** [comment]
Oh, got it.
