### ISSUE TITLE
Game requests

### ISSUE THREAD

**Issue by Richm246** [Tustin/PlayStationDiscord-Games#8]
Hi, I am wondering if the following games could be added please:
inFAMOUS Second Son
LittleBigPlanet 3
Uncharted: The Nathan Drake Collection
Uncharted 4: A Thief's End
The Order: 1866
Ratchet & Clank

**Comment by NPCtom** [comment]
Added

**Comment by NPCtom** [comment]
@Tustin Please respond to pull request
