### ISSUE TITLE
No pictures only text for PS3

### ISSUE THREAD

**Issue by HRVAT007** [Tustin/PlayStationDiscord-Games#96]
As the title says, I’ve downloaded 3.1.2 version since the latest one is bugged and when I open a game on PS3, an example The Last of Us it only says the game name and no picture at all on Discord.

**Comment by PabloGirol** [comment]
Well, the problem is that there isn't any supported games added for ps3/vita at all for now and they might be never implemented as the new API doesn't work with ps3/vita anymore
